  x-airflow-common:
    &airflow-common
    build: ./docker/airflow
    env_file:
      - .env
    environment:
      &airflow-common-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET:-airflow_jwt_secret}
      AIRFLOW__API_AUTH__JWT_ISSUER: ${AIRFLOW__API_AUTH__JWT_ISSUER:-airflow}
      PYTHONPATH: '/opt/airflow'
      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
      AIRFLOW_CONFIG: '/opt/airflow/config/airflow.cfg'
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/airflow/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/airflow/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/airflow/config:/opt/airflow/config
      - ${AIRFLOW_PROJ_DIR:-.}/scripts:/opt/airflow/scripts
      - ${AIRFLOW_PROJ_DIR:-.}/settings:/opt/airflow/settings
      - ${DOCKER_SOCK_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      &airflow-common-depends-on
      postgres:
        condition: service_healthy

  x-spark-common:
    &spark-common
    build: ./docker/spark
    env_file: .env
    volumes:
      - ./scripts/spark_jobs:/opt/spark/jobs

  services:
    postgres:
      image: postgres:16
      environment:
        POSTGRES_USER: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - postgres-db-volume:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}", "-d", "${POSTGRES_DB}"]
        interval: 10s
        retries: 5
        start_period: 5s
      restart: always

    airflow-apiserver:
      <<: *airflow-common
      command: api-server
      ports:
        - "8080:8080"
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/monitor/health"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      restart: always
      depends_on:
        <<: *airflow-common-depends-on
        airflow-init:
          condition: service_completed_successfully

    airflow-scheduler:
      <<: *airflow-common
      command: scheduler
      healthcheck:
        test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      restart: always
      depends_on:
        <<: *airflow-common-depends-on
        airflow-init:
          condition: service_completed_successfully

    airflow-dag-processor:
      <<: *airflow-common
      command: dag-processor
      healthcheck:
        test: ["CMD-SHELL", "airflow jobs check --job-type DagProcessorJob"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      restart: always
      depends_on:
        <<: *airflow-common-depends-on
        airflow-init:
          condition: service_completed_successfully

    airflow-init:
      <<: *airflow-common
      command: version
      environment:
        <<: *airflow-common-env
        _AIRFLOW_DB_MIGRATE: 'true'
        _AIRFLOW_WWW_USER_CREATE: 'true'
        _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USERNAME}
        _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_PASSWORD}
      user: "0:0"

    minio:
      image: minio/minio
      container_name: minio
      ports:
        - "10000:9000"
        - "9002:9001"
      environment:
        MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
        MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
      command: server /mnt/data --console-address ":9001"   
      healthcheck:
        test: ["CMD", "mc", "ready", "local"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - ./minio_data:/mnt/data                            
      
    minio-init-buckets:
      image: minio/minio
      env_file: .env
      entrypoint: >
        /bin/sh -c "
        /usr/bin/mc alias set minio-login $$AWS_ENDPOINT $$AWS_ACCESS_KEY_ID $$AWS_SECRET_ACCESS_KEY;
        /usr/bin/mc mb --ignore-existing minio-login/landing;
        /usr/bin/mc mb --ignore-existing minio-login/bronze;
        /usr/bin/mc mb --ignore-existing minio-login/silver;
        /usr/bin/mc mb --ignore-existing minio-login/spark-logs;
        echo '' | /usr/bin/mc pipe minio-login/spark-logs/events/.keep;
        exit 0;
        "
      depends_on:
        minio:
          condition: service_healthy

    spark-master:
      <<: *spark-common
      container_name: spark-master
      ports:
        - "8090:8080"
        - "7077:7077"
      depends_on:
        minio-init-buckets:
          condition: service_completed_successfully
      command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

    spark-worker:
      <<: *spark-common
      container_name: spark-worker
      depends_on:
        spark-master:
          condition: service_started
      command: >
        /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

    spark-history-server:
      <<: *spark-common
      container_name: spark-history-server
      ports:
        - "18080:18080"
      depends_on: 
        minio:
          condition: service_healthy
        minio-init-buckets:
          condition: service_completed_successfully
      command: >
        /opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer

    pyarrow:
      build: ./docker/pyarrow
      image: pyarrow-custom
      env_file: .env
      container_name: pyarrow
      command: ["python", "-m", "scripts.bronze.bronze_entrypoint"]
      volumes:
        - ./scripts:/scripts
        - ./settings:/settings
  
    pyarrow-build:
      build: ./docker/pyarrow
      image: pyarrow-custom
    
    postgres-test:
      image: postgres:16
      environment:
        POSTGRES_USER: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: airflow_test
      tmpfs:
        - /var/lib/postgresql/data
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}", "-d", "${POSTGRES_DB}"]
        interval: 10s
        retries: 5
        start_period: 5s
      restart: always

    airflow-test:
      <<: *airflow-common
      build: ./docker/airflow-test
      user: "0:0"
      environment:
        <<: *airflow-common-env
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres-test/airflow_test
        _AIRFLOW_DB_MIGRATE: 'true'
      command: ["python", "-m", "pytest", "-vv", "/opt/airflow/tests"]
      volumes:
        - ${AIRFLOW_PROJ_DIR:-.}/airflow/dags:/opt/airflow/dags
        - ${AIRFLOW_PROJ_DIR:-.}/airflow/logs:/opt/airflow/logs
        - ${AIRFLOW_PROJ_DIR:-.}/airflow/config:/opt/airflow/config
        - ${AIRFLOW_PROJ_DIR:-.}/scripts:/opt/airflow/scripts
        - ${AIRFLOW_PROJ_DIR:-.}/settings:/opt/airflow/settings 
        - ${AIRFLOW_PROJ_DIR:-.}/tests/dag_tests:/opt/airflow/tests
      depends_on:
        postgres-test:
          condition: service_healthy
      
    python-test:
      build: ./docker/python-test
      container_name: python-test
      command: ["python", "-m", "pytest", "-vv", "-s", "/include/tests/"]
      volumes:
        - ./scripts:/include/scripts
        - ./settings:/include/settings
        - ./tests/unit_tests:/include/tests/unit_tests
        - ./tests/integration_tests:/include/tests/integration_tests
          
  volumes:
    postgres-db-volume:
